# Dataset split configuration
defaults:
  seed: 42
  splits:
    train: 0.8
    validation: 0.1
    test: 0.1
  stratify:
    - page_type
    - domain

sources:
  navpage_classifier:
    path: data/processed/navpage_classifier_latest.jsonl
    weight: 0.5
  productpage_extractor:
    path: data/processed/productpage_extractor_latest.jsonl
    weight: 0.5

metadata:
  schema_version: "v1"
  description: >
    Placeholder configuration for splitting curated nav-page classifier and product-page extractor datasets
    ahead of Gemma fine-tuning.
