# Packaging configuration for ROCm vLLM artifacts
source:
  checkpoint_dir: models/checkpoints/run_latest
  adapter_dir: models/checkpoints/run_latest/lora

output:
  destination: models/export
  manifest_path: models/export/manifest.json

rocm_vllm:
  precision:
    - bf16
    - fp16
  quantization:
    awq: false
    rtn_int4: false
  tokenizer_padding_side: right

metadata:
  include_files:
    - configs/training.yaml
    - configs/judge_slots.yaml
  extra_notes: >
    Placeholder manifest settings until the packaging pipeline is implemented.
